const initialState = {
    currentUser: {
        uid: 1,
        uName: 'Admin',
    },
    profile: {
        uid: 1,
        firstName: 'Hieu',
        lastName: 'To',
        uName: 'Admin',
        designation: 'IOS Developer',
        createDay: '1 Jan 2013',
        birthDate: '06/05/1985',
        gendar: 'male',
        inforContact: {
            address: '4487 Snowbird Lane',
            city: 'New York',
            country: 'United States',
            pinCode: '10523',
            numberPhone: '631-889-3206'
        },
        inforEducation: {
            institution: 'Oxford University',
            subject: 'Computer Science',
            startingDate: '01/06/2002',
            compelteDate: '31/05/2006',
            degree: 'BE Computer Science',
            grade: 'Grade A',
        },
        inforExperience: {
            companyName: 'Digital Devlopment Inc',
            location: 'United States',
            jobPosition: 'Web Developer',
            periodFrom: '01/07/2007',
            periodTo: '08/06/2018',
        },
        skills:['IOS', 'Android', 'Html', 'CSS', 'Codignitor', 'Php', 'Javascript', 'Wordpress', 'Jquery']
    },
    // ko có currentUser
    listUser: [
        {
            uid: 2,
            uName: 'Mike Litorus',
            companyName: 'Global Technologies',
            designation: 'IOS Developer',
            numberPhone: '9876543210',
            createDay: '1 Jan 2013',
            leaveType: 'Casual Leave',
            dateFrom: '5 May 2017',
            dateTo: '6 May 2017',
            contactPeson: 'Ruby Bartlett',
            noOfDays: 2,
            reason: 'Going to Hospital',
            salary: '38400',
            status: 'Accepted',
            roleId: 1,
        },
        {
            uid: 3,
            uName: 'Richard Miles',
            companyName: 'Preadmin',
            designation: 'Web Developer',
            numberPhone: '9876543210',
            createDay: '1 Jan 2013',
            leaveType: 'Casual Leave',
            dateFrom: '5 May 2017',
            dateTo: '6 May 2017',
            contactPeson: 'Ruby Bartlett',
            noOfDays: 2,
            reason: 'Going to Hospital',
            salary: '38400',
            status: 'Sent',
            roleId: 2,
        },
        {
            uid: 4,
            uName: 'John Doe',
            companyName: 'Preadmin',
            designation: 'Web Designer',
            numberPhone: '9876543210',
            createDay: '1 Jan 2013',
            leaveType: 'Casual Leave',
            dateFrom: '5 May 2017',
            dateTo: '6 May 2017',
            contactPeson: 'Ruby Bartlett',
            noOfDays: 2,
            reason: 'Going to Hospital',
            salary: '38400',
            status: 'Expired',
            roleId: 1,
        },
        {
            uid: 5,
            uName: 'Tarah Shropshire',
            companyName: 'Preadmin',
            designation: 'Android Developer',
            numberPhone: '9876543210',
            createDay: '1 Jan 2013',
            leaveType: 'Casual Leave',
            dateFrom: '5 May 2017',
            dateTo: '6 May 2017',
            contactPeson: 'Ruby Bartlett',
            noOfDays: 2,
            reason: 'Going to Hospital',
            salary: '38400',
            status: 'Accepted',
            roleId: 3,
        },
        {
            uid: 6,
            uName: 'Catherine Manseau',
            companyName: 'Preadmin',
            designation: 'IOS Developer',
            numberPhone: '9876543210',
            createDay: '1 Jan 2013',
            leaveType: 'Casual Leave',
            dateFrom: '5 May 2017',
            dateTo: '6 May 2017',
            contactPeson: 'Ruby Bartlett',
            noOfDays: 2,
            reason: 'Going to Hospital',
            salary: '38400',
            status: 'Accepted',
            roleId: 1,
        },
        {
            uid: 7,
            uName: 'Domenic Houston',
            companyName: 'Preadmin',
            designation: 'Android Developer',
            numberPhone: '9876543210',
            createDay: '1 Jan 2013',
            leaveType: 'Casual Leave',
            dateFrom: '5 May 2017',
            dateTo: '6 May 2017',
            contactPeson: 'Ruby Bartlett',
            noOfDays: 2,
            reason: 'Going to Hospital',
            salary: '38400',
            status: 'Accepted',
            roleId: 1,
        },
        {
            uid: 8,
            uName: 'Buster Wigton',
            companyName: 'Preadmin',
            designation: 'Android Developer',
            numberPhone: '9876543210',
            createDay: '1 Jan 2013',
            leaveType: 'Casual Leave',
            dateFrom: '5 May 2017',
            dateTo: '6 May 2017',
            contactPeson: 'Ruby Bartlett',
            noOfDays: 2,
            reason: 'Going to Hospital',
            salary: '38400',
            status: 'Accepted',
            roleId: 1,
        },
        {
            uid: 9,
            uName: 'Rolland Webber',
            companyName: 'Preadmin',
            designation: 'Web Designer',
            numberPhone: '9876543210',
            createDay: '1 Jan 2013',
            leaveType: 'Casual Leave',
            dateFrom: '5 May 2017',
            dateTo: '6 May 2017',
            contactPeson: 'Ruby Bartlett',
            noOfDays: 2,
            reason: 'Going to Hospital',
            salary: '38400',
            status: 'Accepted',
            roleId: 1,
        },
        {
            uid: 10,
            uName: 'Claire Mapes',
            companyName: 'Preadmin',
            designation: 'Web Developer',
            numberPhone: '9876543210',
            createDay: '1 Jan 2013',
            leaveType: 'Casual Leave',
            dateFrom: '5 May 2017',
            dateTo: '6 May 2017',
            contactPeson: 'Ruby Bartlett',
            noOfDays: 2,
            reason: 'Going to Hospital',
            salary: '38400',
            status: 'Accepted',
            roleId: 1,
        },
        {
            uid: 11,
            uName: 'Melita Faucher',
            companyName: 'Preadmin',
            designation: 'Android Developer',
            numberPhone: '9876543210',
            createDay: '1 Jan 2013',
            leaveType: 'Casual Leave',
            dateFrom: '5 May 2017',
            dateTo: '6 May 2017',
            contactPeson: 'Ruby Bartlett',
            noOfDays: 2,
            reason: 'Going to Hospital',
            salary: '38400',
            status: 'Accepted',
            roleId: 1,
        },
        {
            uid: 12,
            uName: 'Jeffery Lalor',
            companyName: 'Preadmin',
            designation: 'Web Developer',
            numberPhone: '9876543210',
            createDay: '1 Jan 2013',
            leaveType: 'Casual Leave',
            dateFrom: '5 May 2017',
            dateTo: '6 May 2017',
            contactPeson: 'Ruby Bartlett',
            noOfDays: 2,
            reason: 'Going to Hospital',
            salary: '38400',
            status: 'Accepted',
            roleId: 1,
        },
        {
            uid: 13,
            uName: 'Loren Gatlin',
            companyName: 'Preadmin',
            designation: 'IOS Developer',
            numberPhone: '9876543210',
            createDay: '1 Jan 2013',
            leaveType: 'Casual Leave',
            dateFrom: '5 May 2017',
            dateTo: '6 May 2017',
            contactPeson: 'Ruby Bartlett',
            noOfDays: 2,
            reason: 'Going to Hospital',
            salary: '38400',
            status: 'Declined',
            roleId: 1,
        },
        {
            uid: 14,
            uName: 'Tarah Shropshire',
            companyName: 'Preadmin',
            designation: 'Web Developer',
            numberPhone: '9876543210',
            createDay: '1 Jan 2013',
            leaveType: 'Casual Leave',
            dateFrom: '5 May 2017',
            dateTo: '6 May 2017',
            contactPeson: 'Ruby Bartlett',
            noOfDays: 2,
            reason: 'Going to Hospital',
            salary: '38400',
            status: 'Accepted',
            roleId: 1,
        },
    ],
}


const userReducer = (state = initialState, action) => {
    switch (action.type) {
        case "value":

            break;

        default:
            break;
    }
    return {
        ...state
    };
}
export default userReducer;