export const MainNavRender = [
	,
	// {
	// 	type: "",
	// 	path: "",
	// 	exact: "",
	// 	icon: "",
	// 	name: "Main",
	// 	notification: "",
	// 	lists: [],
	// },
	{
		type: "",
		path: "/admin",
		exact: true,
		icon: "fas fa-tachometer-alt",
		name: "Dashboard",
		notification: "",
		lists: [],
		showModal: true,
		// dataTarget: "#add_new",
	},
	{
		type: "",
		path: "/admin/chat",
		icon: "fa fa-comments",
		name: "Chat",
		notification:
			'<span className="badge badge-pill bg-primary float-right">5</span>',
		lists: [],
	},
	{
		index: 0,
		type: "submenu",
		path: "",
		icon: "fas fa-video",
		name: "Calls",
		notification: "",
		lists: [
			{
				path: "/admin/voice-call",
				name: "Voice Call",
				showModal: false,
			},
			{
				path: "/admin/video-call",
				name: "Video Call",
				showModal: false,
			},
			{
				path: "/admin/incoming-call",
				name: "Incoming Call",
				showModal: false,
			},
		],
	},
	{
		index: 1,
		type: "submenu",
		path: "",
		icon: "fa fa-envelope",
		name: "Email",
		notification: "",
		lists: [
			{
				path: "/admin/compose",
				name: "Compose Mail",
				showModal: false,
			},
			{
				path: "/admin/inbox",
				name: "Inbox",
				showModal: false,
			},
			{
				path: "/admin/mail-view",
				name: "Mail View",
				showModal: false,
			},
		],
	},
	{
		type: "",
		path: "/admin/contacts",
		icon: "fa fa-address-card",
		name: "Contacts",
		notification: "",
		lists: [],
	},
	{
		type: "",
		path: "/admin/tasks",
		icon: "fa fa-tasks",
		name: "Tasks",
		notification: "",
		lists: [],
	},
	{
		index: 2,
		type: "submenu",
		path: "",
		icon: "far fa-comment-dots",
		name: "News",
		notification: "",
		lists: [
			{
				path: "/admin/news",
				name: "News",
				showModal: false,
			},
			{
				path: "/admin/news-details",
				name: "News Details",
				showModal: false,
			},
			{
				path: "/admin/add-news",
				name: "Add News",
				dataName: "Add New",
				showModal: true,
				dataTarget: "#add_new",
			},
			{
				path: "/admin/edit-news",
				name: "Edit News",
				dataName: "Edit New",
				showModal: true,
				dataTarget: "#edit_new",
			},
		],
	},
	{
		type: "",
		path: "/admin/tickets",
		icon: "fas fa-ticket-alt",
		name: "Tickets",
		notification: "",
		lists: [],
	},
	{
		type: "",
		path: "/admin/settings",
		icon: "fa fa-cog",
		name: "Settings",
		notification: "",
		lists: [],
	},
];
